app.version=${project.version}
app.github.repo=JCPrieto/Exe-Extractor
app.github.asset.pattern=ExeExtractor-{version}.zip
app.output.zip.name=Exe.zip
app.ui.menu.help=Ayuda
app.ui.menu.about=Acerca de
app.ui.menu.update.available=Nueva version disponible
app.ui.menu.update.tooltip=Descargar la ultima version disponible
app.ui.button.source=Origen
app.ui.button.destination=Destino
app.ui.button.execute=Ejecutar
app.ui.button.continue=Continuar
app.ui.label.select.file=Selecciona archivo
app.ui.label.select.directory=Selecciona directorio
app.ui.text.instructions=-Selecciona el archivo de origen.\n\n-Selecciona la carpeta de destino.\n\n-Ejecutar y listo, ya tienes extraido tu instalador.exe\n\n
app.ui.dialog.info.title=Info
app.ui.dialog.continue.message=Si se han extraido los archivos pulse continuar, en caso contrario espere
app.ui.dialog.error.title=Error
app.ui.info.author=Creado por: <b>Juan Carlos Prieto Silos</b>
app.ui.info.website=Web Site: JCPrieto.es
