/*
 * Inicio.java
 *
 * Created on 10 de marzo de 2007, 19:34
 */

package es.jklabs;

import es.jklabs.file.filter.ExeFilter;
import es.jklabs.utilidades.Constantes;
import es.jklabs.utilidades.Logger;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.nio.file.FileSystems;
import java.util.concurrent.CountDownLatch;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author  Juanky
 */
public class Inicio extends javax.swing.JFrame {
    
    private String rutaArchivo;
    private String rutaSave= "";
    private JMenuItem menuUpdateItem;
    private String updateDownloadUrl;
    
    /** Creates new form Inicio */
    private Inicio() {
        initComponents();
        initUpdateCheck();
    }
    
    private javax.swing.JButton jButton3;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        // Variables declaration - do not modify//GEN-BEGIN:variables
        JMenuBar menuBar = new JMenuBar();
        JMenu menuAyuda = new JMenu("Ayuda");
        JMenuItem menuAcercaDe = new JMenuItem("Acerca de");
        menuUpdateItem = new JMenuItem("Nueva version disponible");
        JButton jButton1 = new JButton();
        jLabel1 = new javax.swing.JLabel();
        JButton jButton2 = new JButton();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        JScrollPane jScrollPane1 = new JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(Constantes.NOMBRE_APP);
        menuAcercaDe.addActionListener(evt -> showInfoDialog());
        menuAyuda.add(menuAcercaDe);
        menuBar.add(menuAyuda);
        menuBar.add(Box.createHorizontalGlue());
        menuUpdateItem.setVisible(false);
        menuUpdateItem.addActionListener(evt -> openUpdateDownload());
        menuUpdateItem.setIcon(loadUpdateIcon());
        menuUpdateItem.setToolTipText("Descargar la ultima version disponible");
        menuUpdateItem.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        menuUpdateItem.setHorizontalTextPosition(SwingConstants.RIGHT);
        menuBar.add(menuUpdateItem);
        setJMenuBar(menuBar);

        jButton1.setText("Origen");
        jButton1.addActionListener(evt2 -> jButton1ActionPerformed());

        jLabel1.setText("Selecciona archivo");

        jButton2.setText("Destino");
        jButton2.addActionListener(evt1 -> jButton2ActionPerformed());

        jLabel2.setText("Selecciona directorio");

        jProgressBar1.setForeground(new java.awt.Color(0, 0, 204));

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("-Selecciona el archivo de origen.\n\n-Selecciona la carpeta de destino.\n\n-Ejecutar y listo, ya tienes extraido tu instalador.exe\n\n");
        jScrollPane1.setViewportView(jTextArea1);

        jButton3.setText("Ejecutar");
        jButton3.setEnabled(false);
        jButton3.addActionListener(evt -> jButton3ActionPerformed());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addComponent(jButton3)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed() {//GEN-FIRST:event_jButton3ActionPerformed
        if (!validarRutas()) {
            return;
        }
        jButton3.setEnabled(false);
        SwingWorker<Void, Integer> worker = new SwingWorker<>() {
            @Override
            protected Void doInBackground() {
                publish(10);
                try {
                    ProcessBuilder processBuilder = new ProcessBuilder(rutaArchivo, "/x", rutaSave);
                    processBuilder.redirectErrorStream(true);
                    Process process = processBuilder.start();
                    publish(50);
                    CountDownLatch latch = new CountDownLatch(1);
                    SwingUtilities.invokeLater(() -> {
                        Continuar c = new Continuar(Inicio.this, false, latch);
                        c.setLocationRelativeTo(Inicio.this);
                        c.setVisible(true);
                    });
                    latch.await();
                    int exitCode = process.waitFor();
                    if (exitCode != 0) {
                        String output = new String(process.getInputStream().readAllBytes(), StandardCharsets.UTF_8);
                        SwingUtilities.invokeLater(() -> showError("Error al extraer el archivo (codigo " + exitCode + ").\n" + output));
                        return null;
                    }
                    String oldName = "%EXENAME%";
                    File newFile = new File(rutaSave + FileSystems.getDefault().getSeparator() + oldName);
                    String newName = "Exe.zip";
                    boolean renamed = newFile.renameTo(new File(rutaSave + FileSystems.getDefault().getSeparator() + newName));
                    SwingUtilities.invokeLater(() -> {
                        if (renamed) {
                            jTextArea1.setText(jTextArea1.getText() + "-El archivo que contiene lo que usted desea se llama Exe.zip");
                        } else {
                            jTextArea1.setText(jTextArea1.getText() + "-No se pudo generar el archivo");
                        }
                    });
                    publish(100);
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                } catch (IOException e) {
                    SwingUtilities.invokeLater(() -> showError("Imposible abrir el archivo."));
                } catch (Exception e) {
                    SwingUtilities.invokeLater(() -> showError("Error inesperado al extraer el archivo."));
                }
                return null;
            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                int value = chunks.getLast();
                jProgressBar1.setValue(value);
            }

            @Override
            protected void done() {
                jButton3.setEnabled(validarRutasSilencioso());
            }
        };
        worker.execute();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed() {//GEN-FIRST:event_jButton2ActionPerformed
        SelectDir sd= new SelectDir();
        Container parent = this.getParent();
        int choice = sd.jFileChooser1.showOpenDialog(parent);
        if (choice == JFileChooser.APPROVE_OPTION){
            rutaSave= sd.jFileChooser1.getSelectedFile().getAbsolutePath();
            this.jLabel2.setText(rutaSave);
            updateExecuteState();
            return;
        }
        updateExecuteState();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed() {//GEN-FIRST:event_jButton1ActionPerformed
        Open o= new Open();
        Container parent = this.getParent();
        int choice = o.jFileChooser1.showOpenDialog(parent);
        if (choice == JFileChooser.APPROVE_OPTION){
            rutaArchivo= o.jFileChooser1.getSelectedFile().getAbsolutePath();
            this.jLabel1.setText(rutaArchivo);
            updateExecuteState();
            return;
        }
        updateExecuteState();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateExecuteState() {
        jButton3.setEnabled(validarRutasSilencioso());
    }

    private boolean validarRutasSilencioso() {
        return validarArchivo(rutaArchivo, false) && validarDirectorio(rutaSave, false);
    }

    private boolean validarRutas() {
        return validarArchivo(rutaArchivo, true) && validarDirectorio(rutaSave, true);
    }

    private boolean validarArchivo(String ruta, boolean mostrarError) {
        if (ruta == null || ruta.isBlank()) {
            if (mostrarError) {
                showError("Selecciona un archivo de origen valido.");
            }
            return false;
        }
        File archivo = new File(ruta);
        if (!archivo.isFile()) {
            if (mostrarError) {
                showError("El archivo de origen no existe.");
            }
            return false;
        }
        return true;
    }

    private boolean validarDirectorio(String ruta, boolean mostrarError) {
        if (ruta == null || ruta.isBlank()) {
            if (mostrarError) {
                showError("Selecciona un directorio de destino valido.");
            }
            return false;
        }
        File dir = new File(ruta);
        if (!dir.isDirectory()) {
            if (mostrarError) {
                showError("El directorio de destino no existe.");
            }
            return false;
        }
        return true;
    }

    private void showInfoDialog() {
        JOptionPane.showMessageDialog(this, "<html><h1>" + Constantes.NOMBRE_APP + " " + Constantes.VERSION + "</h1>" +
                "Creado por: <b>Juan Carlos Prieto Silos</b></html>\n" +
                "Web Site: JCPrieto.es", "Info", JOptionPane.PLAIN_MESSAGE);
    }

    private void initUpdateCheck() {
        if (Constantes.GITHUB_REPO.isEmpty()) {
            return;
        }
        Thread updateThread = new Thread(this::checkForUpdates, "update-check");
        updateThread.setDaemon(true);
        updateThread.start();
    }

    private void checkForUpdates() {
        String apiUrl = "https://api.github.com/repos/" + Constantes.GITHUB_REPO + "/releases/latest";
        try (HttpClient client = HttpClient.newBuilder()
                .followRedirects(HttpClient.Redirect.NORMAL)
                .build()) {
            HttpRequest request = HttpRequest.newBuilder(URI.create(apiUrl))
                    .header("Accept", "application/vnd.github+json")
                    .header("User-Agent", Constantes.NOMBRE_APP)
                    .GET()
                    .build();
            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
            if (response.statusCode() != 200) {
                return;
            }
            String body = response.body();
            String latestVersion = extractJsonValue(body);
            if (latestVersion == null || !isNewerVersion(latestVersion)) {
                return;
            }
            String downloadUrl = extractAssetUrl(body, latestVersion);
            if (downloadUrl == null) {
                return;
            }
            SwingUtilities.invokeLater(() -> {
                updateDownloadUrl = downloadUrl;
                menuUpdateItem.setText("Nueva version disponible (" + normalizeVersion(latestVersion) + ")");
                menuUpdateItem.setVisible(true);
            });
        } catch (Exception e) {
            Logger.error("Comprobar actualizaciones", e);
        }
    }

    private void openUpdateDownload() {
        if (updateDownloadUrl == null || updateDownloadUrl.isEmpty()) {
            return;
        }
        try {
            Desktop.getDesktop().browse(URI.create(updateDownloadUrl));
        } catch (Exception e) {
            Logger.error("Abrir descarga de actualizacion", e);
        }
    }

    private ImageIcon loadUpdateIcon() {
        java.net.URL iconUrl = Inicio.class.getClassLoader().getResource("img/icons/update.png");
        if (iconUrl == null) {
            return null;
        }
        return new ImageIcon(iconUrl);
    }

    private String extractJsonValue(String json) {
        Pattern pattern = Pattern.compile("\"" + Pattern.quote("tag_name") + "\"\\s*:\\s*\"([^\"]+)\"");
        Matcher matcher = pattern.matcher(json);
        if (matcher.find()) {
            return matcher.group(1);
        }
        return null;
    }

    private String extractAssetUrl(String json, String latestVersion) {
        String desiredAssetName = buildAssetName(latestVersion);
        if (desiredAssetName != null && !desiredAssetName.isEmpty()) {
            Pattern namedAsset = Pattern.compile("\\{[^}]*\"name\"\\s*:\\s*\"" +
                    Pattern.quote(desiredAssetName) +
                    "\"[^}]*\"browser_download_url\"\\s*:\\s*\"([^\"]+)\"");
            Matcher matcher = namedAsset.matcher(json);
            if (matcher.find()) {
                return matcher.group(1);
            }
        }
        Pattern zipAsset = Pattern.compile("\"browser_download_url\"\\s*:\\s*\"([^\"]+\\.zip)\"");
        Matcher matcher = zipAsset.matcher(json);
        if (matcher.find()) {
            return matcher.group(1);
        }
        return null;
    }

    private String buildAssetName(String latestVersion) {
        if (Constantes.GITHUB_ASSET_PATTERN == null || Constantes.GITHUB_ASSET_PATTERN.isEmpty()) {
            return null;
        }
        String normalizedVersion = normalizeVersion(latestVersion);
        return Constantes.GITHUB_ASSET_PATTERN.replace("{version}", normalizedVersion);
    }

    private boolean isNewerVersion(String latestVersion) {
        int comparison = compareVersionParts(normalizeVersion(Constantes.VERSION), normalizeVersion(latestVersion));
        return comparison < 0;
    }

    private String normalizeVersion(String version) {
        if (version == null) {
            return "";
        }
        String normalized = version.trim();
        if (normalized.startsWith("v") || normalized.startsWith("V")) {
            normalized = normalized.substring(1);
        }
        return normalized;
    }

    private int compareVersionParts(String currentVersion, String latestVersion) {
        String[] currentParts = currentVersion.split("\\.");
        String[] latestParts = latestVersion.split("\\.");
        int max = Math.max(currentParts.length, latestParts.length);
        for (int i = 0; i < max; i++) {
            int current = i < currentParts.length ? parseVersionPart(currentParts[i]) : 0;
            int latest = i < latestParts.length ? parseVersionPart(latestParts[i]) : 0;
            if (current != latest) {
                return Integer.compare(current, latest);
            }
        }
        return currentVersion.compareTo(latestVersion);
    }

    private int parseVersionPart(String part) {
        Matcher matcher = Pattern.compile("^(\\d+)").matcher(part);
        if (matcher.find()) {
            return Integer.parseInt(matcher.group(1));
        }
        return 0;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        Logger.eliminarLogsVacios();
        Logger.init();
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            java.awt.EventQueue.invokeLater(() -> new Inicio().setVisible(true));
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                UnsupportedLookAndFeelException e) {
            Logger.error("Cargar el LookAndFeel del S.O", e);
        }
    }

    public static class Open extends javax.swing.JFrame {
        
    private javax.swing.JFileChooser jFileChooser1;
    
    /** Creates new form Open */
    Open() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">                          
    private void initComponents() {
        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            jFileChooser1.setFileFilter(new ExeFilter());

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );
            pack();
        }
    
    }

    public static class SelectDir extends javax.swing.JFrame {
    
    /** Creates new form SelectDir */
    SelectDir() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">                          
    private void initComponents() {
        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        jFileChooser1.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>                        
    
    
    // Variables declaration - do not modify                     
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration                   
    
}

    public static class Continuar extends javax.swing.JDialog {
        private final CountDownLatch latch;
    
    /** Creates new form Continuar */
    Continuar(java.awt.Frame parent, boolean modal, CountDownLatch latch) {
        super(parent, modal);
        this.latch = latch;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">                          
    private void initComponents() {
        JLabel jLabel = new JLabel();
        // Variables declaration - do not modify
        JButton jButton1 = new JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jLabel.setText("Si se han extraido los archivos pulse continuar, en caso contrario espere");

        jButton1.setText("Continuar");
        jButton1.addActionListener(evt -> jButton1ActionPerformed());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed() {
        latch.countDown();
        dispose();
    }

     // End of variables declaration

    
}

    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;

    private void showError(String message) {
        JOptionPane.showMessageDialog(new Frame(), message, "Error", JOptionPane.ERROR_MESSAGE);
    }
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    
}
